// temporaryReducer

export const RESET_TEMPORARY_REDUCER = 'RESET_TEMPORARY_REDUCER'
export const SET_TEMPORARY_VALUE = 'SET_TEMPORARY_VALUE'
export const TRY_RECOVER_PASSWORD = 'TRY_RECOVER_PASSWORD'
export const TRY_LOGIN = 'TRY_LOGIN'
export const SET_IS_LOADING = 'SET_IS_LOADING'
export const TRY_RESET_PASSWORD = 'TRY_RESET_PASSWORD'
export const CHECK_HASH_RESET_PASSWORD = 'CHECK_HASH_RESET_PASSWORD'
export const REMOVE_TEMPORARY_ERRORS = 'REMOVE_TEMPORARY_ERRORS'
export const CHANGE_TAB = 'CHANGE_TAB'

// notificationReducer

export const RESET_NOTIFICATION_REDUCER = 'RESET_NOTIFICATION_REDUCER'
export const SEND_NOTIFICATION = 'SEND_NOTIFICATION'
export const SEND_PERSISTENT_NOTIFICATION = 'SEND_PERSISTENT_NOTIFICATION'
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'

// loginReducer

export const TRY_FACEBOOK_LOGIN = 'TRY_FACEBOOK_LOGIN'
export const TRY_GOOGLE_LOGIN = 'TRY_GOOGLE_LOGIN'
export const FAILED_LOGIN = 'FAILED_LOGIN'
export const SET_LOGIN_VALUE = 'SET_LOGIN_VALUE'
export const RESET_LOGIN_REDUCER = 'RESET_LOGIN_REDUCER'
export const DO_LOGOUT_CLEANUP = 'DO_LOGOUT_CLEANUP'

// registerReducer

export const RESET_REGISTER_REDUCER = 'RESET_REGISTER_REDUCER'
export const SET_REGISTER_VALUE = 'SET_REGISTER_VALUE'
export const TRY_REGISTER = 'TRY_REGISTER'

// settingsReducer

export const RESET_SETTINGS_REDUCER = 'RESET_SETTINGS_REDUCER'
export const SET_SETTINGS_VALUE = 'SET_SETTINGS_VALUE'

// updateProfile

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const RESET_UPDATE_PROFILE_REDUCER = 'RESET_UPDATE_PROFILE_REDUCER'
export const SET_UPDATE_PROFILE_VALUE = 'SET_UPDATE_PROFILE_VALUE'
export const TRY_SET_UPDATE_PROFILE_VALUE = 'TRY_SET_UPDATE_PROFILE_VALUE'
export const SET_OPEN_EDIT_PROFILE_MODAL = 'SET_OPEN_EDIT_PROFILE_MODAL'
export const TRY_CHANGE_AVATAR = 'TRY_CHANGE_AVATAR'

// scheduceReducer

export const RESET_SCHEDULE_REDUCER = 'RESET_SCHEDULE_REDUCER'
export const SET_SCHEDULE_VALUES = 'SET_SCHEDULE_VALUES'
export const SET_SCHEDULE_TEMP_VALUE = 'SET_SCHEDULE_TEMP_VALUE'
export const RESET_SCHEDULE_TEMP_VALUES = 'RESET_SCHEDULE_TEMP_VALUES'
